config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  scope "(:locale)", locale: /en|zh-cn/ do
    devise_for :users
    root 'staticpages#home'
    resources :product_categories do
      resources :products, only: [:index]
    end
    resources :products, only: [:index]
    resources :introductions_product do
      collection do
        get 'fabric'
        get 'technology'
      end
    end
    resources :introductions_company, only: [:index]
    resources :locations, only: [:index]
    resources :services do
      collection do
        get 'group_customization'
        get 'individual_customization'
        get 'oem_odm'
      end
    end
    resources :join_us, only: [:index]
    resources :sale_sites do
      collection do
        get 'contact_us'
        get 'stores'
        get 'sale_network'
      end
    end
  end

  match '*path'                       => redirect('/'),                       via: [:get]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    if user && user.admin?
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :manage, :all                  # allow access to dashboard
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :locations
end

app/models/location.rb
class Location < ActiveRecord::Base
  validates_presence_of :city_id
  belongs_to :city
end

app/models/product.rb
class Product < ActiveRecord::Base
  translates :name
  belongs_to :product_category
  accepts_nested_attributes_for :translations, allow_destroy: true

  has_attached_file :image,

      :styles => {  :thumbnail => {:geometry => '560x750#'}},
      :url => ":normalized_image_file_name_:style.:extension",
      :path => ":rails_root/public/:normalized_image_file_name_:style.:extension",
      :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


  Paperclip.interpolates :normalized_image_file_name do |attachment, style|
    attachment.instance.normalized_image_file_name
  end

  def normalized_image_file_name
    "/web/products/#{self.id}/images/"
  end

end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  translates :name
  has_many :products
  accepts_nested_attributes_for :translations, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def admin?
    admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale
  before_action :get_categories

  def set_locale
    if self.kind_of? RailsAdmin::ApplicationController
      I18n.locale = :en
    else
      I18n.locale = params[:locale] || I18n.default_locale
    end
  end

  def default_url_options(options = {})
    {locale: I18n.locale}
  end

  def get_categories
    @categories = ProductCategory.all
  end
end

app/controllers/join_us_controller.rb
class JoinUsController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @cities    =  City.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #before_action :set_product, only: [:show, :edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    @categories = ProductCategory.all

    @products = Product.where(product_category_id:(params[:product_category_id]))

    @current_category = ProductCategory.find(params[:product_category_id])
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name)
    end
end

app/controllers/sale_sites_controller.rb
class SaleSitesController < ApplicationController
  def contact_us
  end

  def stores
  end

  def sale_network
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def group_customization
  end

  def individual_customization
  end

  def oem_odm
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def language_name(locale)
    case locale
      when :'en' then "English"
      when :'zh-cn' then "中文"
      else locale
    end
  end
end

app/helpers/introductions_company_helper.rb
module IntroductionsCompanyHelper
end

app/helpers/introductions_product_helper.rb
module IntroductionsProductHelper
end

app/helpers/join_us_helper.rb
module JoinUsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sale_sites_helper.rb
module SaleSitesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/join_us/index.html.erb
<div class="join_us">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 introduction">
        <div class="col-xs-12 col-sm-8 col-md-5">
          <div class="col-xs-12 col-md-10 col-md-offset-1">
            <div>
              <h1><%= t('join_us.title') %></h1>
              <%= t('join_us.information').html_safe %>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/sale_sites/contact_us.html.erb
<div class="container">
  <div class="contact-us">
    <h1><span><%= t('contact_us.title') %></span></h1>

    <div>
      <!--引用百度地图API-->
      <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=232FMZtcONtLNXnhASK59WZU"></script>
      <!--百度地图容器-->
      <div style="width:100%;height:300px;border:#ccc solid 1px;font-size:12px" id="map"></div>
      <script type="text/javascript">
        //创建和初始化地图函数：
        function initMap(){
          createMap();//创建地图
          setMapEvent();//设置地图事件
          addMapControl();//向地图添加控件
          addMapOverlay();//向地图添加覆盖物
        }
        function createMap(){
          map = new BMap.Map("map");
          map.centerAndZoom(new BMap.Point(121.439468,31.25749),17);
        }
        function setMapEvent(){
          map.enableKeyboard();
          map.enableDragging();
          map.enableDoubleClickZoom();
          map.disableScrollWheelZoom();
        }
        function addClickHandler(target,window){
          target.addEventListener("click",function(){
            target.openInfoWindow(window);
          });
        }
        function addMapOverlay(){
          var markers = [
            {content:"上海市普陀区光新路88号1705-1706室",title:"澜维奥",imageOffset: {width:-46,height:-21},position:{lat:31.25756,lng:121.439248}}
          ];
          for(var index = 0; index < markers.length; index++ ){
            var point = new BMap.Point(markers[index].position.lng,markers[index].position.lat);
            var marker = new BMap.Marker(point,{icon:new BMap.Icon("http://api.map.baidu.com/lbsapi/createmap/images/icon.png",new BMap.Size(20,25),{
              imageOffset: new BMap.Size(markers[index].imageOffset.width,markers[index].imageOffset.height)
            })});
            var label = new BMap.Label(markers[index].title,{offset: new BMap.Size(25,5)});
            var opts = {
              width: 200,
              title: markers[index].title,
              enableMessage: false
            };
            var infoWindow = new BMap.InfoWindow(markers[index].content,opts);
            marker.setLabel(label);
            addClickHandler(marker,infoWindow);
            map.addOverlay(marker);
          };
        }
        //向地图添加控件
        function addMapControl(){
          var scaleControl = new BMap.ScaleControl({anchor:BMAP_ANCHOR_BOTTOM_LEFT});
          scaleControl.setUnit(BMAP_UNIT_IMPERIAL);
          map.addControl(scaleControl);
          var navControl = new BMap.NavigationControl({anchor:BMAP_ANCHOR_TOP_LEFT,type:BMAP_NAVIGATION_CONTROL_LARGE});
          map.addControl(navControl);
          var overviewControl = new BMap.OverviewMapControl({anchor:BMAP_ANCHOR_BOTTOM_RIGHT,isOpen:true});
          map.addControl(overviewControl);
        }
        var map;
        initMap();
      </script>
    </div>
    <Br>
    <p><%= t('contact_us.tel') %>：021-32551608</p>
    <p><%= t('contact_us.fax') %>：021-32551628</p>
    <p><%= t('contact_us.address') %>：上海市普陀区光新路88号1705-1706室</p>
  </div>

</div>

app/views/sale_sites/sale_network.html.erb
<div class="sale_network">
  <div class="container">
    <div class="clearfix">
      <div class="">
        <div class="col-xs-12">
          <h1><%= t('sale_network.title') %></h1>
          <p><%= t('sale_network.information1') %></p>
          <p><%= t('sale_network.information2') %></p>
          <div>
            <%= image_tag 'sale_network.jpg' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sale_sites/stores.html.erb
<div class="store-image">
  <div class="container">
    <div class="clearfix">
      <div class="">
        <div class="col-xs-12"><h1><%= t('store_image.title') %></h1></div>
        <div class="col-xs-12"><p><%= t('sale_network.information2') %></p></div>
        <div class="image  row">
          <div class="col-xs-12 col-md-6">
            <%= image_tag 'store_image_01.jpg' %>
          </div>
          <div class="col-xs-12 col-md-6">
            <%= image_tag 'store_image_02.jpg' %>
          </div>
          <div class="col-xs-12 col-md-6">
            <%= image_tag 'store_image_03.jpg' %>
          </div>
          <div class="col-xs-12 col-md-6">
            <%= image_tag 'store_image_04.jpg' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/services/group_customization.html.erb
<!-- Begin Main -->
<div role="main" class="">

  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <aside class="sidebar sidebar-padding">
          <aside class="block blk-cat">
            <ul class="list-unstyled list-cat">
              <li><%= link_to t('service.title1'), group_customization_services_path, class: "#{'active' if current_page?(group_customization_services_path)}" %></li>
              <li><%= link_to t('service.title2'), individual_customization_services_path, class: "#{'active' if current_page?(individual_customization_services_path)}" %></li>
              <li><%= link_to t('service.title3'), oem_odm_services_path, class: "#{'active' if current_page?(oem_odm_services_path)}" %></li>
            </ul>
          </aside>
        </aside>
      </div>
      <div class="col-md-9 introduction-product">
        <div>
          <div class="row">
            <h2 class="col-xs-12"><%= t('service.title1') %></h2>
            <div class="col-xs-12">
              <p><%= t('service.information1') %></p>
            </div>
            <div class="col-xs-12">
              <div class="col-xs-12 col-sm-6 col-md-3">
                <%= image_tag 'service_01.jpg' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


  </div>

</div>
<!-- End Main -->

app/views/services/index.html.erb
<div class="introduction-service">
  <div class="container">
    <div class="">
      <h2><%= t('service.title1') %></h2>
      <div class="row">
        <div class="col-xs-12">
          <p><%= t('service.information1') %></p>
        </div>
        <div class="col-xs-12">
          <div class="col-xs-3">
            <%= image_tag 'service_01.jpg' %>
          </div>
        </div>
      </div>
      <br>
      <h2><%= t('service.title2') %></h2>
      <div class="row">
        <div class="col-xs-12">
          <p><%= t('service.information3') %></p>
        </div>
        <div class="col-xs-12">
          <div class="col-xs-3">
            <%= image_tag 'service_02.jpg' %>
          </div>
          <div class="col-xs-3">
            <%= image_tag 'service_03.jpg' %>
          </div>
          <div class="col-xs-3">
            <%= image_tag 'service_04.jpg' %>
          </div>
        </div>
      </div>
      <br>
      <h2><%= t('service.title3') %></h2>
      <div class="row">
        <div class="col-xs-12">
          <p><%= t('service.information3') %></p>
        </div>
        <div class="col-xs-12">
          <div class="col-xs-3">
            <%= image_tag 'service_05.jpg' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/services/individual_customization.html.erb
<!-- Begin Main -->
<div role="main" class="">

  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <aside class="sidebar sidebar-padding">
          <aside class="block blk-cat">
            <ul class="list-unstyled list-cat">
              <li><%= link_to t('service.title1'), group_customization_services_path, class: "#{'active' if current_page?(group_customization_services_path)}" %></li>
              <li><%= link_to t('service.title2'), individual_customization_services_path, class: "#{'active' if current_page?(individual_customization_services_path)}" %></li>
              <li><%= link_to t('service.title3'), oem_odm_services_path, class: "#{'active' if current_page?(oem_odm_services_path)}" %></li>
            </ul>
          </aside>
        </aside>
      </div>
      <div class="col-md-9 introduction-product">
        <div>
          <div class="row">
            <h2 class="col-xs-12"><%= t('service.title2') %></h2>
            <div class="col-xs-12">
              <p><%= t('service.information2') %></p>
            </div>
            <div class="col-xs-12">
              <div class="col-xs-12 col-sm-6 col-md-3">
                <%= image_tag 'service_02.jpg' %>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-3">
                <%= image_tag 'service_03.jpg' %>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-3">
                <%= image_tag 'service_04.jpg' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


  </div>

</div>
<!-- End Main -->

app/views/services/oem_odm.html.erb
<!-- Begin Main -->
<div role="main" class="">

  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <aside class="sidebar sidebar-padding">
          <aside class="block blk-cat">
            <ul class="list-unstyled list-cat">
              <li><%= link_to t('service.title1'), group_customization_services_path, class: "#{'active' if current_page?(group_customization_services_path)}" %></li>
              <li><%= link_to t('service.title2'), individual_customization_services_path, class: "#{'active' if current_page?(individual_customization_services_path)}" %></li>
              <li><%= link_to t('service.title3'), oem_odm_services_path, class: "#{'active' if current_page?(oem_odm_services_path)}" %></li>
            </ul>
          </aside>
        </aside>
      </div>
      <div class="col-md-9 introduction-product">
        <div>
          <div class="row">
            <h2 class="col-xs-12"><%= t('service.title3') %></h2>
            <div class="col-xs-12">
              <p><%= t('service.information3') %></p>
            </div>
            <div class="col-xs-12">
              <div class="col-xs-12 col-sm-6 col-md-3">
                <%= image_tag 'service_05.jpg' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


  </div>

</div>
<!-- End Main -->

app/views/staticpages/home.html.erb
<div role="main" class="main">
  <!-- Begin Main Slide -->
  <section class="main-slide">
    <div id="owl-main-demo" class="owl-carousel main-demo">
      <div class="item" id="item1"><img src="images/content/slides/slider1.jpg" class="img-responsive" alt="Photo">
      </div>
      <div class="item" id="item2"><img src="images/content/slides/slider2.jpg" class="img-responsive" alt="Photo">
      </div>
      <div class="item" id="item3"><img src="images/content/slides/slider3.jpg" class="img-responsive" alt="Photo">
      </div>
    </div>
  </section>
  <!-- End Main Slide -->

  <!-- Begin Ads -->
  <!--  <section class="ads">
      <div class="container">
        <div class="row">
          <div class="col-xs-4 animation">
            <a href="#"><img src="images/content/products/ad-1.png" class="img-responsive" alt="Ad"></a>
          </div>
          <div class="col-xs-4 animation">
            <a href="#"><img src="images/content/products/ad-1.png" class="img-responsive" alt="Ad"></a>
          </div>
          <div class="col-xs-4 animation">
            <a href="#"><img src="images/content/products/ad-1.png" class="img-responsive" alt="Ad"></a>
          </div>
        </div>
      </div>
    </section>-->
  <!-- End Ads -->

  <!-- Begin Latest Blogs -->
  <section class="latest-blog home-introduction">
    <div class="container">
      <h2 class="title"><span><%= t('header.introduction') %></span></h2>

      <div class="row">
        <div class="col-xs-12 col-md-6 animation">
          <article class="post">
            <a href="<%= introductions_company_index_path %>">
            <div class="post-image">
              <span class="post-info-act">
                <p>
                    <span><%= t('company_introduction.title') %></span>
                </p>
              </span>

              <%= image_tag 'cuff_home.jpg', class: "img-responsive" %>
            </div>
            </a>
          </article>
        </div>
        <div class="col-xs-12 col-md-6 animation">
          <article class="post">
            <a href="<%= technology_introductions_product_index_path %>">
            <div class="post-image">
              <span class="post-info-act">
                <p>
                  <span><%= t('product_introduction.title') %></span>
                </p>
              </span>
              <%= image_tag 'tie_home.jpg', class: "img-responsive" %>
            </div>
            </a>
          </article>
        </div>
      </div>
    </div>
  </section>
  <!-- End Latest Blogs -->

  <!-- Begin Parallax -->
  <section class="pi-parallax hidden-xs" data-stellar-background-ratio="0.6">
    <div class="container">
      <div id="owl-text-slide" class="owl-carousel">
        <div class="item">
          <blockquote>
            <p><%= t('info1') %></p>
            <footer><cite>LANUVIO</cite></footer>
          </blockquote>
        </div>
        <div class="item">
          <blockquote>
            <p><%= t('info2') %></p>
            <footer><cite>LANUVIO</cite></footer>
          </blockquote>
        </div>
      </div>
    </div>
  </section>
  <!-- End Parallax -->

  <!-- Begin New Products -->
  <section class="product-tab">
    <div class="container">
      <h2 class="title"><span><%= t('header.product') %></span></h2>
      <!-- Nav tabs -->
      <!--<ul class="nav nav-tabs pro-tabs text-center animation" role="tablist">
        <li class="active"><a href="#man" role="tab" data-toggle="tab">Clothes</a></li>
        <li><a href="#accesories" role="tab" data-toggle="tab">Accesories</a></li>
      </ul>-->

      <!-- Tab panes -->
      <div class="tab-content">

        <div class="row">
          <div class="col-xs-12 animation">
            <div class="product">
              <div class="product-thumb-info">
                <div class="product-thumb-info-image">
                  <a href="<%= product_category_products_url(1) %>">
                    <%= image_tag 'product_overview_top.jpg', class: 'img-responsive' %>
                  </a>
                </div>
              </div>
            </div>
          </div>
          <!--<div class="col-xs-6 col-sm-3 animation">
              <div class="product">
                <div class="product-thumb-info">
                  <div class="product-thumb-info-image">
                    <a href="<%= product_category_products_url(1) %>">
                      <%= image_tag 'product_classical_02.jpg', class: 'img-responsive' %>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xs-6 col-sm-3 animation">
              <div class="product">
                <div class="product-thumb-info">
                  <div class="product-thumb-info-image">
                    <a href="<%= product_category_products_url(1) %>">
                      <%= image_tag 'product_classical_03.jpg', class: 'img-responsive' %>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xs-6 col-sm-3 animation">
              <div class="product">
                <div class="product-thumb-info">
                  <div class="product-thumb-info-image">
                    <a href="<%= product_category_products_url(1) %>">
                      <%= image_tag 'product_classical_04.jpg', class: 'img-responsive' %>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xs-6 col-sm-3 animation">
              <div class="product">
                <div class="product-thumb-info">
                  <div class="product-thumb-info-image">
                    <a href="<%= product_category_products_url(2) %>">
                      <%= image_tag 'product_fashion_02.jpg', class: 'img-responsive' %>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xs-6 col-sm-3 animation">
            <div class="product">
              <div class="product-thumb-info">
                <div class="product-thumb-info-image">
                  <a href="<%= product_category_products_url(2) %>">
                    <%= image_tag 'product_fashion_03.jpg', class: 'img-responsive' %>
                  </a>
                </div>
              </div>
            </div>
          </div>
            <div class="col-xs-6 col-sm-3 animation">
              <div class="product">
                <div class="product-thumb-info">
                  <div class="product-thumb-info-image">
                    <a href="<%= product_category_products_url(2) %>">
                      <%= image_tag 'product_fashion_04.jpg', class: 'img-responsive' %>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xs-6 col-sm-3 animation">
              <div class="product">
                <div class="product-thumb-info">
                  <div class="product-thumb-info-image">
                    <a href="<%= product_category_products_url(3) %>">
                      <%= image_tag 'product_leisure_02.jpg', class: 'img-responsive' %>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xs-6 col-sm-3 animation">
              <div class="product">
                <div class="product-thumb-info">
                  <div class="product-thumb-info-image">
                    <a href="<%= product_category_products_url(3) %>">
                      <%= image_tag 'product_leisure_03.jpg', class: 'img-responsive' %>
                    </a>
                  </div>
                </div>
              </div>
            </div>-->

        </div>
      </div>

    </div>
  </section>
  <!-- End New Products -->
</div>