config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  scope "(:locale)", locale: /en|zh-cn/ do
    devise_for :users
    root 'staticpages#home'
    resources :product_categories do
      resources :products, only: [:index]
    end
    resources :products, only: [:index]
    resources :introductions_product do
      collection do
        get 'fabric'
        get 'technology'
      end
    end
    resources :introductions_company, only: [:index]
    resources :locations, only: [:index]
    resources :services do
      collection do
        get 'group_customization'
        get 'individual_customization'
        get 'oem_odm'
      end
    end
    resources :join_us, only: [:index]
    resources :sale_sites do
      collection do
        get 'contact_us'
        get 'stores'
        get 'sale_network'
      end
    end
  end

  match '*path'                       => redirect('/'),                       via: [:get]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    if user && user.admin?
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :manage, :all                  # allow access to dashboard
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :locations
end

app/models/location.rb
class Location < ActiveRecord::Base
  validates_presence_of :city_id
  belongs_to :city
end

app/models/product.rb
class Product < ActiveRecord::Base
  translates :name
  belongs_to :product_category
  accepts_nested_attributes_for :translations, allow_destroy: true

  has_attached_file :image,

      :styles => {  :thumbnail => {:geometry => '560x750#'}},
      :url => ":normalized_image_file_name_:style.:extension",
      :path => ":rails_root/public/:normalized_image_file_name_:style.:extension",
      :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


  Paperclip.interpolates :normalized_image_file_name do |attachment, style|
    attachment.instance.normalized_image_file_name
  end

  def normalized_image_file_name
    "/web/products/#{self.id}/images/"
  end

end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  translates :name
  has_many :products
  accepts_nested_attributes_for :translations, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def admin?
    admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale
  before_action :get_categories

  def set_locale
    if self.kind_of? RailsAdmin::ApplicationController
      I18n.locale = :en
    else
      I18n.locale = params[:locale] || I18n.default_locale
    end
  end

  def default_url_options(options = {})
    {locale: I18n.locale}
  end

  def get_categories
    @categories = ProductCategory.all
  end
end

app/controllers/join_us_controller.rb
class JoinUsController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @cities    =  City.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #before_action :set_product, only: [:show, :edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    @categories = ProductCategory.all

    @products = Product.where(product_category_id:(params[:product_category_id]))

    @current_category = ProductCategory.find(params[:product_category_id])
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name)
    end
end

app/controllers/sale_sites_controller.rb
class SaleSitesController < ApplicationController
  def contact_us
  end

  def stores
  end

  def sale_network
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def group_customization
  end

  def individual_customization
  end

  def oem_odm
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def language_name(locale)
    case locale
      when :'en' then "English"
      when :'zh-cn' then "中文"
      else locale
    end
  end
end

app/helpers/join_us_helper.rb
module JoinUsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sale_sites_helper.rb
module SaleSitesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
<!--    <div class="upper-foot">
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <h2><#%= t('contact') %></h2>
          <address>
            <i class="fa fa-map-marker"></i><%#= t('address') %><br>
            <i class="fa fa-phone"></i> 021-32551608<br>
            <i class="fa fa-fax"></i>021-32551628<br>
          </address>
        </div>
        <div class="col-xs-12 col-sm-6">
          <a class="logo" href="<%#= root_path %>"><%#= image_tag 'logo_white.png', style:'height:33px;' %></a>
        </div>
        &lt;!&ndash;<div class="col-xs-12 col-sm-4">
          <h2>Useful links</h2>
          <ul class="list-unstyled">
            <li><a href="#">Track Orders</a></li>
            <li><a href="#">FAQs</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Free Credit Report</a></li>
            <li><a href="#">Terms and Conditions</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Community Guidelines</a></li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-4">
          <h2>Don’t miss out</h2>
          <p>In venenatis neque a eros laoreet eu placerat erat suscipit. Fusce cursus, erat ut scelerisque.</p>
          <form class="form-inline form-newsletter" role="form">
            <div class="form-group">
              <label class="sr-only" for="exampleInputEmail2">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Enter your email here">
            </div>
            <button type="submit" class="btn"><i class="fa fa-caret-right"></i></button>
          </form>
        </div>&ndash;&gt;
      </div>
    </div>-->
    <div class="below-foot">
      <div class="row">
        <div class="col-xs-6 copyrights">
          <p>Copyright © 2015 Laiweiao<br>
            All rights reserved.</p>
        </div>
        <div class="col-xs-6 text-right">
          <ul class="list-inline social-list">
            <li><a class="jiathis_button_weixin" title="wechat" href="javascript:;" target="_blank"><i class="fa fa-wechat"></i></a></li>
            <li><a class="jiathis_button_tsina" title="weibo" href="javascript:;" target="_blank"><i class="fa fa-weibo"></i></a></li>
            <li><a class="jiathis_button_renren" title="renren" href="javascript:;" target="_blank"><i class="fa fa-renren"></i></a></li>
            <li><a class="jiathis_button_fb" title="Facebook" href="javascript:;" target="_blank"><i class="fa fa-facebook"></i></a></li>
            <li><a class="jiathis_button_twitter" title="Twitter" href="javascript:;" target="_blank"><i class="fa fa-twitter"></i></a></li>

          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

<!--include social share js-->
<script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=1410333261952403" charset="utf-8"></script>
<!--include social share js end-->

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-main navbar-main-slide" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        <a class="logo" href="<%= root_path %>"><%= image_tag 'logo_chinese_white.png', style:'height:33px;' %></a>
      </div>
      <ul class="nav navbar-nav navbar-act pull-right">
        <!--<li class="login"><a href="javascript:void(0);"><i class="fa fa-user"></i></a></li>-->
        <!--<li class="search"><a href="javascript:void(0);" data-toggle="modal" data-target=".bs-example-modal-lg"><i class="fa fa-search"></i></a></li>-->

      </ul>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav pull-right">
          <li class="<% if current_page?(root_path) %>active<% end %>"><a href="<%= root_path %>"><%= t('home') %></a></li>
          <li class="dropdown <% if params[:controller] == "products" %>active<% end %>"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('header.product') %></a>
            <ul class="dropdown-menu">
              <% @categories.each do |category| %>
                <li><%= link_to category.name, product_category_products_url(category) %></li>
              <% end %>
            </ul>
          <!--            <div class="dropdown-menu">
              <div class="mega-menu-content">
                <div class="row">
                  <div class="col-md-6 menu-column">
                    <h3><%#= t('category') %></h3>
                    <ul class="list-unstyled sub-menu">
                      <li><a href="#">衬衫</a></li>
                      <li><a href="#">西装</a></li>
                    </ul>
                  </div>

                  <div class="col-md-6 menu-column">
                    <h3><%#= t('accessories') %></h3>
                    <ul class="list-unstyled sub-menu">
                      <li><a href="#">领带</a></li>
                      <li><a href="#">袖口</a></li>
                      <li><a href="#">皮带</a></li>
                      <li><a href="#">皮鞋</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>-->
          </li>
          <li class="dropdown <% if current_page?(introductions_company_index_path) || current_page?(technology_introductions_product_index_path) || current_page?(fabric_introductions_product_index_path) %>active<% end %>"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('header.introduction') %></a>
            <ul class="dropdown-menu">
              <li><a href="<%= introductions_company_index_path %>"><%= t('company_introduction.title') %></a></li>
              <li><a href="<%= technology_introductions_product_index_path %>"><%= t('product_introduction.title') %></a></li>
            </ul>
          </li>
          <li class="dropdown <% if params[:controller] == "sale_sites" %>active<% end %>"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('contact') %></a>
            <ul class="dropdown-menu">
              <li><a href="<%= stores_sale_sites_path %>"><%= t('store_image.title') %></a></li>
              <li><a href="<%= sale_network_sale_sites_path %>"><%= t('sale_network.title') %></a></li>
              <li><a href="<%= contact_us_sale_sites_path %>"><%= t('contact') %></a></li>
            </ul>
          </li>
          <li class="dropdown <% if params[:controller] == "services" || current_page?(join_us_path) %>active<% end %>"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('header.service_cooperate') %></a>
            <ul class="dropdown-menu">
              <li><a href="<%= group_customization_services_path %>"><%= t('service.title') %></a></li>
              <li><a href="<%= join_us_path %>"><%= t('header.join_us') %></a></li>
            </ul>
          </li>
          <li>
            <% I18n.available_locales.each do |locale| %>
              <%= content_tag(:li, link_to(language_name(locale), {locale: locale}, {data: {no_turbolink: true}})) unless locale == I18n.locale %>
            <% end %>
          </li>

        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </nav>
</header>

<!-- Begin Search -->
<!--<div class="modal fade bs-example-modal-lg search-wrapper" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <p class="clearfix"><button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button></p>
      <form class="form-inline form-search" role="form">
        <div class="form-group">
          <label class="sr-only" for="textsearch">Enter text search</label>
          <input type="text" class="form-control input-lg" id="textsearch" placeholder="Enter text search">
        </div>
        <button type="submit" class="btn btn-white">Search</button>
      </form>
    </div>
  </div>
</div>-->
<!-- End Search -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="keywords" content="laiweiao,lanuvio,澜维奥,好衬衫,好面料，源于意大利" />
  <meta name="description" content="laiweiao lanuvio 澜维奥">
  <meta name="author" content="Justin">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>澜维奥</title>
  <%= stylesheet_link_tag    'application', media: nil %>
  <%= javascript_include_tag 'application' %>

  <!--[if lt IE 9]>
  <script src="/javascripts/html5shiv.js" type="text/javascript"></script>
  <script src="/javascripts/respond.min.js" type="text/javascript"></script>
  <![endif]-->
  <%= csrf_meta_tags %>


</head>
<body class="black">
  <div>
    <%= render 'layouts/header' %>
      <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>